apiVersion: v1
kind: Service
metadata:
  name: {{ include "beacon.fullname" . }}-api
  labels:
    {{- include "beacon.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5050
      targetPort: 5050
      name: beacon-api
  selector:
    {{ include "beacon.selectorLabels" . | nindent 4 }}
    app: beacon
