apiVersion: v1
kind: Secret
metadata:
  name: {{ include "beacon.fullname" . }}
stringData:
  conf.py: |
    import logging
    import yaml
    import aiohttp.web as web
    from beacon.exceptions.exceptions import FileNotFound

    try:
        with open("beacon/conf/api_version.yml") as api_version_file:
            api_version_yaml = yaml.safe_load(api_version_file)
    except Exception as e:
        raise FileNotFound('There are issues with the api_version.yml file. Check if it can be opened or if has any content')

    level = logging.{{ .Values.beacon.config.logLevel | default "INFO" }}
    log_file = {{ if .Values.beacon.config.logFile }}"{{ .Values.beacon.config.logFile }}"{{ else }}None{{ end }}
    beacon_id = '{{ .Values.beacon.config.beaconId }}'
    beacon_name = '{{ .Values.beacon.config.beaconName }}'
    api_version = '{{ .Values.beacon.config.apiVersion }}'
    uri = '{{ .Values.beacon.config.uri }}'
    uri_subpath = '{{ .Values.beacon.config.uriSubpath }}'
    complete_url = uri + uri_subpath
    environment = '{{ .Values.beacon.config.environment }}'
    description = r"{{ .Values.beacon.config.description }}"
    version = api_version_yaml['api_version']
    welcome_url = '{{ .Values.beacon.config.welcomeUrl }}'
    alternative_url = '{{ .Values.beacon.config.alternativeUrl }}'
    create_datetime = '{{ if .Values.beacon.config.createDatetime }}{{ .Values.beacon.config.createDatetime }}{{ else }}{{ dig "metadata" "creationTimestamp" (now) (lookup "v1" "Secret" .Release.Namespace (include "beacon.fullname" .)) }}{{ end }}'
    update_datetime = '{{ if .Values.beacon.config.updateDatetime }}{{ .Values.beacon.config.updateDatetime }}{{ else }}{{ dateInZone "2006-01-02T15:04:05Z" (now) "UTC" }}{{ end }}'
    default_beacon_granularity = "{{ .Values.beacon.config.defaultBeaconGranularity }}"
    security_levels = [{{ range $index, $level := .Values.beacon.config.securityLevels }}{{ if $index }}, {{ end }}'{{ $level }}'{{ end }}]
    documentation_url = '{{ .Values.beacon.config.documentationUrl }}'
    cors_urls = [{{ range $index, $url := .Values.beacon.config.corsUrls }}{{ if $index }}, {{ end }}"{{ $url }}"{{ end }}]

    # Service Info
    ga4gh_service_type_group = '{{ .Values.beacon.config.ga4ghServiceTypeGroup }}'
    ga4gh_service_type_artifact = '{{ .Values.beacon.config.ga4ghServiceTypeArtifact }}'
    ga4gh_service_type_version = '{{ .Values.beacon.config.ga4ghServiceTypeVersion }}'

    # Organization info
    org_id = '{{ .Values.beacon.config.orgId }}'
    org_name = '{{ .Values.beacon.config.orgName }}'
    org_description = '{{ .Values.beacon.config.orgDescription }}'
    org_adress = '{{ .Values.beacon.config.orgAddress }}'
    org_welcome_url = '{{ .Values.beacon.config.orgWelcomeUrl }}'
    org_contact_url = '{{ .Values.beacon.config.orgContactUrl }}'
    org_logo_url = '{{ .Values.beacon.config.orgLogoUrl }}'
    org_info = '{{ .Values.beacon.config.orgInfo }}'

    # Certificates
    beacon_server_crt = '{{ .Values.beacon.config.beaconServerCrt }}'
    beacon_server_key = '{{ .Values.beacon.config.beaconServerKey }}'

    # Query Budget
    query_budget_per_user = {{ .Values.beacon.config.queryBudgetPerUser | ternary "True" "False" }}
    query_budget_per_ip = {{ .Values.beacon.config.queryBudgetPerIp | ternary "True" "False" }}
    query_budget_amount = {{ .Values.beacon.config.queryBudgetAmount }}
    query_budget_time_in_seconds = {{ .Values.beacon.config.queryBudgetTimeInSeconds }}
    query_budget_database = '{{ .Values.beacon.config.queryBudgetDatabase }}'
    query_budget_db_name = '{{ .Values.beacon.config.queryBudgetDbName }}'
    query_budget_table = '{{ .Values.beacon.config.queryBudgetTable }}'

    # Query Rounding
    imprecise_count = {{ .Values.beacon.config.impreciseCount }}
    round_to_tens = {{ .Values.beacon.config.roundToTens | ternary "True" "False" }}
    round_to_hundreds = {{ .Values.beacon.config.roundToHundreds | ternary "True" "False" }}
