apiVersion: v1
kind: Secret
metadata:
  name: {{ include "beacon.fullname" . }}-mongo
data:
  {{- $secretName := printf "%s-mongo" (include "beacon.fullname" .) }}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}

  {{- if $existingSecret}}
  password: {{ index $existingSecret.data "password" }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}