apiVersion: v1
kind: Service
metadata:
 name: {{ .Release.Name }}
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: rpc
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: {{ .Release.Name }}
