oidc:
  enabled: false
  url: XXX
  redirecturl: XXX
  clientid: XXX
  clientsecret: XXX
  audience: XXX

compute: kubernetes

pvc:
 name: storage
 existing: false
 storageClass: nfs-csi
 size: 2Gi

htsget:
  # Leave empty to disable HTSGET storage entirely.
  serviceUrl: ""
  timeout: 30s

basicauth:
  user: XXX
  password: XXX

rpcclient:
  user: XXX
  password: XXX

image: XXX

funnel:
  resources:
    limits:
      cpu: 2
      memory: 4Gi
      ephemeral-storage: 25Gi
    requests:
      cpu: 100m
      memory: 4Gi
      ephemeral-storage: 25Gi
  serviceAccount: funnel-sa
  runAsUser: 1000
  seccompProfile: true
  imagePullSecret: ""

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host: XXX
