apiVersion: v1
kind: Service
metadata:
  name: {{ include "fdp.fullname" . }}-client
  labels:
    {{- include "fdp.labels" . | nindent 4 }}
    app: fdp-client
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "fdp.selectorLabels" . | nindent 4 }}
    app: fdp-client