apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fdp.fullname" . }}-configuration
  labels:
    {{- include "fdp.labels" . | nindent 4 }}
type: Opaque
stringData:
  application.yml: |
    logging:
      level:
        root: DEBUG
    instance:
      clientUrl: {{ .Values.server.config.clientUrl }}
      persistentUrl: {{ .Values.server.config.persistentUrl }}
    repository:
      type: 2
      native:
        dir: /data
    ping:
      endpoint: https://home.fairdatapoint.org
      interval: 18000000
    security:
      jwt:
        token:
          secret-key: {{ .Values.server.config.jwtSecret }}
    spring:
      data:
        mongodb:
          uri: mongodb://{{ .Values.mongodb.bootstrap.username }}:${MONGO_PASSWORD}@{{ include "fdp.fullname" . }}-mongo:27017/{{ .Values.mongodb.bootstrap.db }}?authSource=admin
