apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fdp.fullname" . }}-server
  labels:
    {{- include "fdp.labels" . | nindent 4 }}
    app: fdp-server
spec:
  selector:
    matchLabels:
      {{- include "fdp.selectorLabels" . | nindent 6 }}
      app: fdp-server
  template:
    metadata:
      labels:
        {{- include "fdp.selectorLabels" . | nindent 8 }}
        app: fdp-server
    spec:
      {{- with .Values.server.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: fdp
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          env:
          {{- with .Values.server.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
            - name:  MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "fdp.fullname" . }}-mongo
                  key: password

          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /fdp/application.yml
              subPath: application.yml
            - name: data
              mountPath: /data
      volumes:
        - name: config
          secret:
            secretName: {{ include "fdp.fullname" . }}-configuration
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "fdp.fullname" . }}-data